import type { CurriculumPack } from './types';

export const aqaPack: CurriculumPack = {
  id: 'aqa',
  curriculumValues: ['AQA'],
  authority: 'AQA',
  displayName: 'AQA — Guideline Pack',
  coverage: 'guideline',
  lastReviewed: '2026-08-17',
  sourceNotes: [
    'Maintainer-only source note; do not inject into learner-facing output. This pack is a practical planning guideline, not an official or verified AQA document.',
    'Maintainer-only public overview: AQA subjects: https://www.aqa.org.uk/subjects.',
    'Maintainer-only public overview: AQA qualifications: https://www.aqa.org.uk/qualifications.',
    'Use the current AQA specification supplied by the school or teacher for official subject content, identifiers, assessment requirements, and terminology.',
    'This pack deliberately avoids reproducing specification codes, unit codes, paper numbers, Assessment Objective labels, grade boundaries, mark schemes, or complete official command-word lists.',
  ],
  applicability: [
    'Use for AQA GCSE and AQA A-Level or AS planning language when AQA is the named board.',
    'Keep AQA visible in the planning context: this is not a generic UK GCSE pack, a Pearson Edexcel or OCR guide, or a Cambridge IGCSE guide.',
    'Use the current AQA specification that the school actually teaches for official course details; this pack supplies planning cues only.',
    'Do not transfer AQA assumptions to Pearson Edexcel, OCR, Cambridge, or a locally authored programme.',
  ],
  uiHelperText:
    'Guideline pack for AQA GCSE and A-Level planning language. Not official or verified. Not Edexcel, OCR, or Cambridge.',
  terminology: [
    'Name AQA and the current AQA subject specification supplied by the school when setting the planning context; do not invent course identifiers or official requirements.',
    'Use learning intention, success criteria, modelling, guided practice, independent application, retrieval, misconception, feedback, and reflection as practical AQA planning language.',
    'Use knowledge, application, analysis, and evaluation in plain language when they describe the intended thinking; never turn them into numbered labels.',
    'If an uploaded AQA specification exists, use only identifiers and terminology that appear in it. Without one, use plain-language descriptions rather than guessing AQA-specific detail.',
    'Refer to required practicals only as a general science-planning category, and refer to NEA only as a general coursework or extended-production category when relevant.',
    'Never invent a required-practical list, NEA task, component, submission requirement, weighting, or assessment rule.',
    'Use subject vocabulary precisely and pre-teach essential terms, especially where English is an additional language for some learners.',
    'Keep the cognitive demand high while providing language access through visuals, worked examples, sentence stems, glossaries, structured talk, and opportunities to rehearse ideas.',
    'Treat exam-style command-word practice as support for communicating subject understanding, not as a complete official command-word list or a substitute for teaching the underlying knowledge and skills.',
  ],
  assessmentStyle: [
    'Begin with a short retrieval or diagnostic check that reveals prerequisite knowledge, misconceptions, and language needs in the AQA course context.',
    'Make success criteria observable and specific enough for students to judge whether they can demonstrate the intended knowledge or skill.',
    'Gather evidence during modelling, guided practice, questioning, discussion, practical work, and independent application, then adjust the lesson in response.',
    'Use short responses, annotated diagrams, worked solutions, explanations, data interpretation, practical records, or extended writing according to the subject.',
    'Use AQA-flavoured exam-style practice only when it serves the learning intention; never fabricate official scoring, grade boundaries, identifiers, or assessment materials.',
    'If an uploaded AQA specification exists, use only assessment language and identifiers that appear in it; otherwise assess knowledge, application, analysis, and evaluation in plain language.',
    'Keep required practicals and NEA at category level only: plan the relevant learning, evidence, skills, or production process without inventing lists or tasks.',
    'End with an exit check that identifies secure learning, partial understanding, and the next reteach, practice, intervention, or extension step.',
    'Provide feedback that tells students what is accurate, what needs improvement, and what they should do next; include structured self- or peer-review where appropriate.',
  ],
  lessonExpectations: [
    'Write a clear AQA GCSE or A-Level learning intention that identifies the knowledge, concept, skill, or method students should demonstrate by the end of the lesson.',
    'Pair it with concise success criteria describing visible performance and expected quality without inventing AQA course identifiers.',
    'Open with purposeful retrieval, a diagnostic question, or a motivating context, then make the relevance of the new learning explicit.',
    'Use explicit teaching and modelling, think aloud about disciplinary choices, and check understanding before guided practice and independent application.',
    'Plan questioning from secure recall towards explanation, application, comparison, interpretation, or evaluation as appropriate for the subject and AQA course context.',
    'Make misconceptions, vocabulary demands, scaffolds, grouping, resources, timings, and adaptations visible in the plan.',
    'Support EAL and ESL learners with pre-taught vocabulary, clear instructions, visuals, sentence frames, structured partner talk, and models of strong responses without reducing subject demand.',
    'Include a meaningful independent or collaborative product and exam-style practice only when they reinforce the learning intention and do not rely on invented official assessment materials.',
    'For science, treat required practical work as a category for planning investigation skills and evidence; for relevant subjects, treat NEA as a category for planning production and feedback.',
    'Close with reflection or exit evidence that informs the next lesson, homework, intervention, or enrichment rather than simply ending the activity.',
  ],
  subjectNotes: {
    Mathematics: [
      'State whether the lesson focuses on fluency, conceptual understanding, reasoning, problem solving, or a connected progression of these.',
      'Model representations and more than one valid strategy where useful, asking students to explain why a method works rather than only reproduce steps.',
      'Use worked examples, deliberate practice, error analysis, and carefully sequenced challenge to expose and address misconceptions.',
      'Pre-teach mathematical vocabulary and use sentence stems so EAL and ESL learners can explain relationships, methods, and reasoning precisely.',
      'Use AQA as the named planning context while keeping examples and assessment claims tied to the supplied course document.',
    ],
    English: [
      'Make the learning intention measurable through a specific reading, writing, speaking, listening, vocabulary, grammar, or integrated language performance.',
      'Use an appropriate text or model, demonstrate the target skill, guide students through evidence and structure, and then provide time for independent production.',
      'Teach vocabulary and literary or language terminology in context, using glossaries, sentence frames, and structured discussion where they improve access.',
      'Use success criteria for meaning, evidence, organisation, accuracy, and audience, and give students a supported opportunity to revise their work.',
      'Refer to NEA only as a general category when it is relevant to the uploaded course; do not invent an NEA task, component, or submission requirement.',
      'Keep reading and writing decisions anchored in the supplied AQA course rather than importing Pearson Edexcel, OCR, or Cambridge conventions.',
    ],
    Science: [
      'Anchor the lesson in explaining a concept, applying scientific knowledge, planning an investigation, interpreting evidence, or evaluating a claim.',
      'Make practical work explicit about the question, prediction, variables, safety expectations, roles, recording method, and evidence-based conclusion.',
      'Use models, diagrams, prediction questions, hinge questions, and data interpretation to reveal misconceptions before independent application.',
      'Pre-teach scientific vocabulary and response structures so EAL and ESL learners can communicate precise explanations without lowering the scientific demand.',
      'Refer to required practical work only as a general category unless the uploaded specification supplies the relevant official detail; never invent a practical list.',
      'Use AQA science language only at the level supported by the supplied specification, with required practicals remaining a category rather than a prescribed list.',
    ],
    'Computer Science': [
      'Make the computational learning intention visible through decomposition, abstraction, algorithms, programming, data representation, systems, or digital problem solving as appropriate.',
      'Model the reasoning and debugging process, then move from a small guided example to independent or paired construction, testing, and explanation.',
      'Use trace tables, annotated pseudocode, diagrams, test cases, and precise technical vocabulary to make computational thinking observable.',
      'Support EAL and ESL learners with visual representations, carefully sequenced instructions, and language frames for describing logic, errors, and design decisions.',
      'Plan computational examples in the AQA context without inventing a course sequence, assessment identifier, or official task.',
    ],
    History: [
      'Frame the lesson around chronological understanding, causation, consequence, change and continuity, significance, interpretation, or the use of evidence.',
      'Model how to select and explain relevant evidence, distinguish a source from an interpretation, and build a supported historical explanation.',
      'Use timelines, source comparison, structured debate, and paragraph frames before asking students to produce an independent response.',
      'Pre-teach historical vocabulary and provide language support while preserving opportunities for students to weigh evidence and communicate a reasoned judgement.',
      'Use the supplied AQA history course for content selection; this pack does not assert a prescribed topic, depth study, or sequence.',
    ],
    Geography: [
      'Connect the learning intention to geographical knowledge, place, processes, patterns, data, fieldwork, human-environment relationships, or decision making.',
      'Model how to read maps, diagrams, photographs, graphs, and data, then require students to explain patterns with accurate geographical vocabulary.',
      'Use local, regional, and global examples where they clarify the concept, without adding irrelevant case-study detail or implying an official specification sequence.',
      'Support EAL and ESL learners with labelled visuals, vocabulary banks, sentence stems, and structured interpretation before independent analysis.',
      'Use AQA geography as the planning context while leaving examples, fieldwork, and case studies to the supplied course document.',
    ],
  },
};

export const AQA_PACK = aqaPack;
