import type { CurriculumPack } from './types';

export const edexcelPack: CurriculumPack = {
  id: 'edexcel',
  curriculumValues: ['Edexcel'],
  authority: 'EDEXCEL',
  displayName: 'Edexcel — Guideline Pack',
  coverage: 'guideline',
  lastReviewed: '2026-08-17',
  sourceNotes: [
    'Maintainer source: Pearson Qualifications public overview pages at https://qualifications.pearson.com/en/qualifications.html and https://qualifications.pearson.com/en/support/support-for-you/teachers.html.',
    'These public overview pages provide orientation only; this pack is not official, verified, or a reproduction of Pearson Edexcel specification content.',
    'Use the current Pearson Edexcel specification supplied by the school for official subject content, assessment requirements, identifiers, and terminology.',
    'Source notes are maintainer-only and must not be injected into generated lesson content.',
  ],
  applicability: [
    'Use for Pearson Edexcel GCSE and A-Level / AS planning language when Pearson Edexcel is the named board.',
    'Treat Pearson Edexcel GCSE and A-Level planning as a linear course journey: build, revisit, and connect learning across the taught course rather than inventing modular routes.',
    'This is not a guide for AQA, OCR, Cambridge International, or a generic unnamed-board GCSE course.',
    'Use the current Pearson Edexcel specification the school actually teaches for official course details; this pack supplies planning cues only.',
  ],
  uiHelperText:
    'Guideline pack for Pearson Edexcel GCSE and A-Level planning language. Not official or verified. Not AQA, OCR, or Cambridge.',
  terminology: [
    'Name Pearson Edexcel as the board in the planning context and use Pearson Edexcel GCSE or A-Level language where it helps the teacher distinguish this pack.',
    'Plan a linear Pearson Edexcel course through cumulative sequencing, spaced retrieval, deliberate revisiting, and explicit links between prior and current learning.',
    'Use learning intention, success criteria, modelling, guided practice, independent application, retrieval, misconception, feedback, and reflection as practical planning language.',
    'Use plain-language prompts such as describe, explain, apply, analyse, and evaluate to shape classroom tasks when they suit the intended thinking.',
    'If an uploaded Pearson Edexcel specification exists, use only identifiers and terminology that appear in it; do not create official-looking labels or assessment requirements.',
    'Without an uploaded specification, describe knowledge, application, analysis, and evaluation in plain language rather than implying an official structure.',
    'Use subject vocabulary precisely and pre-teach essential terms, especially where English is an additional language for some learners.',
    'Keep the cognitive demand high while providing language access through visuals, worked examples, sentence stems, glossaries, structured talk, and opportunities to rehearse ideas.',
  ],
  assessmentStyle: [
    'Begin with a short retrieval or diagnostic check that reveals prerequisite knowledge, misconceptions, and language needs within the linear Pearson Edexcel course.',
    'Make success criteria observable and specific enough for students to judge whether they can demonstrate the intended knowledge or skill.',
    'Gather evidence during modelling, guided practice, questioning, discussion, practical work, and independent application, then adjust the lesson in response.',
    'Use short responses, annotated diagrams, worked solutions, explanations, data interpretation, practical records, or extended writing according to the subject.',
    'Use Pearson Edexcel-aware exam-style practice when it serves the learning intention, but do not invent official scoring, identifiers, grade boundaries, or assessment materials.',
    'Use cumulative checks that revisit earlier learning as well as the current lesson, reflecting the linear GCSE or A-Level planning context.',
    'If the teacher uploads the current Pearson Edexcel specification, use only assessment language and identifiers that appear in it; otherwise assess in plain language.',
    'Provide feedback that tells students what is accurate, what needs improvement, and what they should do next; include structured self- or peer-review where appropriate.',
    'End with an exit check that identifies secure learning, partial understanding, and the next reteach, practice, intervention, or extension step.',
  ],
  lessonExpectations: [
    'Write a clear Pearson Edexcel GCSE or A-Level learning intention that identifies the knowledge, concept, skill, or method students should demonstrate by the end of the lesson.',
    'Pair it with concise success criteria describing visible performance and expected quality within the linear course journey.',
    'Open with purposeful retrieval, a diagnostic question, or a motivating context, then make the relevance of the new learning explicit.',
    'Use explicit teaching and modelling, think aloud about disciplinary choices, and check understanding before guided practice and independent application.',
    'Plan questioning from secure recall towards explanation, application, analysis, comparison, interpretation, or evaluation as appropriate for the subject and class.',
    'Make misconceptions, vocabulary demands, scaffolds, grouping, resources, timings, and adaptations visible in the plan.',
    'Support EAL and ESL learners with pre-taught vocabulary, clear instructions, visuals, sentence frames, structured partner talk, and models of strong responses without reducing subject demand.',
    'Build independent application and exam-style practice from the current learning while deliberately reconnecting it to earlier parts of the linear course.',
    'Use real-world application when it reinforces the learning intention, without implying a Pearson Edexcel-prescribed example or official task.',
    'Close with reflection or exit evidence that informs the next lesson, homework, intervention, or enrichment rather than simply ending the activity.',
  ],
  subjectNotes: {
    Mathematics: [
      'State whether the lesson focuses on fluency, conceptual understanding, reasoning, problem solving, or a connected progression of these.',
      'Model representations and more than one valid strategy where useful, asking students to explain why a method works rather than only reproduce steps.',
      'Use worked examples, deliberate practice, error analysis, and carefully sequenced challenge to expose and address misconceptions.',
      'Pre-teach mathematical vocabulary and use sentence stems so EAL and ESL learners can explain relationships, methods, and reasoning precisely.',
      'Use cumulative retrieval and connected representations so the Pearson Edexcel linear course does not become a sequence of isolated topics.',
    ],
    English: [
      'Make the learning intention measurable through a specific reading, writing, speaking, listening, vocabulary, grammar, or integrated language performance.',
      'Use an appropriate text or model, demonstrate the target skill, guide students through evidence and structure, and then provide time for independent production.',
      'Teach vocabulary and literary or language terminology in context, using glossaries, sentence frames, and structured discussion where they improve access.',
      'Use success criteria for meaning, evidence, organisation, accuracy, and audience, and give students a supported opportunity to revise their work.',
      'Plan reading and writing as a cumulative Pearson Edexcel journey, revisiting analytical and crafted-writing decisions across the course.',
    ],
    Science: [
      'Anchor the lesson in explaining a concept, applying scientific knowledge, planning an investigation, interpreting evidence, or evaluating a claim.',
      'Make practical work explicit about the question, prediction, variables, safety expectations, roles, recording method, and evidence-based conclusion.',
      'Use models, diagrams, prediction questions, hinge questions, and data interpretation to reveal misconceptions before independent application.',
      'Pre-teach scientific vocabulary and response structures so EAL and ESL learners can communicate precise explanations without lowering the scientific demand.',
      'Revisit scientific ideas and investigative reasoning across the Pearson Edexcel linear course rather than treating each lesson as a standalone unit.',
    ],
    'Computer Science': [
      'Make the computational learning intention visible through decomposition, abstraction, algorithms, programming, data representation, systems, or digital problem solving as appropriate.',
      'Model the reasoning and debugging process, then move from a small guided example to independent or paired construction, testing, and explanation.',
      'Use trace tables, annotated pseudocode, diagrams, test cases, and precise technical vocabulary to make computational thinking observable.',
      'Support EAL and ESL learners with visual representations, carefully sequenced instructions, and language frames for describing logic, errors, and design decisions.',
      'Sequence programming, data, and systems learning cumulatively in the Pearson Edexcel context without inventing official course identifiers.',
    ],
    History: [
      'Frame the lesson around chronological understanding, causation, consequence, change and continuity, significance, interpretation, or the use of evidence.',
      'Model how to select and explain relevant evidence, distinguish a source from an interpretation, and build a supported historical explanation.',
      'Use timelines, source comparison, structured debate, and paragraph frames before asking students to produce an independent response.',
      'Pre-teach historical vocabulary and provide language support while preserving opportunities for students to weigh evidence and communicate a reasoned judgement.',
      'Use cumulative chronological and evidential links appropriate to linear Pearson Edexcel planning without asserting a prescribed topic sequence.',
    ],
    Geography: [
      'Connect the learning intention to geographical knowledge, place, processes, patterns, data, fieldwork, human-environment relationships, or decision making.',
      'Model how to read maps, diagrams, photographs, graphs, and data, then require students to explain patterns with accurate geographical vocabulary.',
      'Use local, regional, and global examples where they clarify the concept, without adding irrelevant case-study detail or implying an official specification sequence.',
      'Support EAL and ESL learners with labelled visuals, vocabulary banks, sentence stems, and structured interpretation before independent analysis.',
      'Revisit geographical processes, data, and examples across the Pearson Edexcel linear course while leaving official content choices to the supplied specification.',
    ],
  },
};

export const EDEXCEL_PACK = edexcelPack;
