import Link from 'next/link';
import { legalConfig, operatorLabel } from '@/lib/legal/config';

export function PrivacyPolicyContent() {
  const {
    serviceName,
    contactEmail,
    physicalAddress,
    websiteUrl,
    effectiveDate,
    accountDeletionGraceDays,
    paymentProcessor,
    dataHostingRegion,
  } = legalConfig;

  return (
    <>
      <section>
        <p>
          This Privacy Policy explains how {operatorLabel()} (&quot;we&quot;, &quot;us&quot;, or
          &quot;our&quot;) collects, uses, stores, and shares personal information when you use{' '}
          {serviceName} at{' '}
          <a href={websiteUrl}>{websiteUrl}</a> (the &quot;Service&quot;). We are based in South
          Africa and process personal information in accordance with the Protection of Personal
          Information Act, 2013 (POPIA) and, where applicable, the EU General Data Protection
          Regulation (GDPR) and similar laws.
        </p>
      </section>

      <section>
        <h2>1. Who we are</h2>
        <p>
          <strong>Service:</strong> {serviceName}
          <br />
          <strong>Responsible party:</strong> {operatorLabel()}
          <br />
          <strong>Address:</strong> {physicalAddress}
          <br />
          <strong>Privacy contact:</strong>{' '}
          <a href={`mailto:${contactEmail}`}>{contactEmail}</a>
        </p>
      </section>

      <section>
        <h2>2. Information we collect</h2>
        <p>We collect the following categories of personal information:</p>

        <h3>Account and profile information</h3>
        <ul>
          <li>Email address, display name, and authentication credentials (or Google sign-in profile data)</li>
          <li>Teaching preferences you provide during onboarding or in Settings: default subject, grade or year group, and curriculum</li>
          <li>Subscription plan, trial status, generation usage counts, and account creation date</li>
        </ul>

        <h3>Content you provide</h3>
        <ul>
          <li>Lesson plans generated and stored in your account (title, subject, grade, curriculum, duration, structured lesson content)</li>
          <li>Documents you upload (PDF, DOCX, XLSX) such as curriculum documents and lesson templates</li>
          <li>Text extracted from uploaded documents to align AI-generated lesson plans with your curriculum</li>
          <li>Prompts and instructions you enter when generating a lesson</li>
          <li>Exported files (DOCX, XLSX) created from your lesson plans</li>
        </ul>

        <h3>Payment information</h3>
        <ul>
          <li>
            If you subscribe to a paid plan, {paymentProcessor} processes your payment. We receive
            billing metadata (such as customer and subscription identifiers and plan status) but do
            not store your full card number on our servers.
          </li>
        </ul>

        <h3>Technical and usage information</h3>
        <ul>
          <li>Essential session cookies set by Supabase to keep you signed in</li>
          <li>Server and hosting logs (IP address, browser type, request timestamps) generated by our hosting provider</li>
          <li>AI usage metadata such as model used and token counts associated with lesson generation</li>
        </ul>

        <p>
          We do <strong>not</strong> use advertising cookies, Google Analytics, or similar marketing
          trackers at launch.
        </p>
      </section>

      <section>
        <h2>3. How we use your information</h2>
        <p>We process personal information for these lawful purposes (POPIA Condition 6):</p>
        <ul>
          <li>
            <strong>Providing the Service:</strong> creating and managing your account, generating
            lesson plans, storing your content, and enabling exports
          </li>
          <li>
            <strong>AI processing:</strong> sending lesson prompts and relevant curriculum text to AI
            providers so they can generate lesson content for you
          </li>
          <li>
            <strong>Billing:</strong> managing subscriptions, trials, and payments through{' '}
            {paymentProcessor}
          </li>
          <li>
            <strong>Security and abuse prevention:</strong> authenticating users, enforcing plan
            limits, and protecting the Service
          </li>
          <li>
            <strong>Support and communications:</strong> responding to your requests and sending
            service-related messages
          </li>
          <li>
            <strong>Legal compliance:</strong> meeting legal obligations and responding to lawful
            requests
          </li>
        </ul>
      </section>

      <section>
        <h2>4. AI and third-party processors</h2>
        <p>
          We use trusted third parties to operate {serviceName}. They process data only as needed to
          provide their service to us:
        </p>
        <ul>
          <li>
            <strong>Supabase</strong> — authentication, database, and private file storage for your
            uploads and account data (hosted in {legalConfig.supabaseRegion})
          </li>
          <li>
            <strong>Anthropic</strong> — processes lesson prompts and curriculum context to generate
            lesson plans for paid (Pro and Pro+) subscribers using Claude models
          </li>
          <li>
            <strong>Google</strong> — provides Gemini models for free-tier lesson generation and,
            if you choose &quot;Continue with Google&quot;, OAuth sign-in (email and basic profile
            only)
          </li>
          <li>
            <strong>{paymentProcessor}</strong> — payment processing for paid subscriptions; card
            details are handled by {paymentProcessor}, not stored by us
          </li>
          <li>
            <strong>Vercel</strong> — application hosting, CDN, and infrastructure logs (hosted in{' '}
            {legalConfig.vercelRegion})
          </li>
        </ul>
        <p>
          When you generate a lesson plan, the text you provide (including extracted curriculum
          content from uploads) is transmitted to the applicable AI provider for that request. Do not
          upload documents containing unnecessary personal information about students or colleagues.
        </p>
      </section>

      <section>
        <h2>5. International data transfers</h2>
        <p>
          Your data may be stored and processed in {dataHostingRegion}. Our processors may also
          process data in other countries. Where required by POPIA (Condition 8) and GDPR, we rely
          on appropriate safeguards such as processor agreements and standard contractual clauses
          offered by our providers. By using the Service, you acknowledge that cross-border
          transfers may occur to deliver the Service.
        </p>
      </section>

      <section>
        <h2>6. Cookies</h2>
        <p>
          We use essential cookies required for authentication and session management (via Supabase).
          These are strictly necessary to operate the Service and do not require a marketing cookie
          banner. We do not set non-essential tracking cookies at launch.
        </p>
      </section>

      <section>
        <h2>7. Data retention</h2>
        <ul>
          <li>
            <strong>Active accounts:</strong> we retain your account data and content while your
            account is active
          </li>
          <li>
            <strong>Account deletion:</strong> when you delete your account, we schedule permanent
            deletion of your personal data within {accountDeletionGraceDays} days. During this grace
            period your account is deactivated and you cannot sign in. Contact us if you need
            immediate deletion
          </li>
          <li>
            <strong>Billing records:</strong> we may retain limited billing and transaction records
            as required by tax and accounting law after account deletion
          </li>
          <li>
            <strong>Server logs:</strong> hosting logs are retained for a limited period for security
            and troubleshooting
          </li>
        </ul>
      </section>

      <section>
        <h2>8. Security</h2>
        <p>
          We implement reasonable technical and organisational measures to protect your information,
          including HTTPS encryption in transit, access controls, row-level security in our
          database, and private storage buckets for uploaded files. No method of transmission or
          storage is completely secure.
        </p>
      </section>

      <section>
        <h2>9. Your rights</h2>
        <p>Depending on your location, you may have the right to:</p>
        <ul>
          <li>Access the personal information we hold about you</li>
          <li>Correct inaccurate information (via Settings or by contacting us)</li>
          <li>Request deletion of your account and personal data</li>
          <li>Export your lesson plans before deletion</li>
          <li>Object to or restrict certain processing where applicable</li>
          <li>Lodge a complaint with the Information Regulator (South Africa) or your local supervisory authority</li>
        </ul>
        <p>
          To exercise these rights, email{' '}
          <a href={`mailto:${contactEmail}`}>{contactEmail}</a> or delete your account in{' '}
          <Link href="/settings">Settings</Link>. We will respond within the timeframes required by
          applicable law.
        </p>
      </section>

      <section>
        <h2>10. Children</h2>
        <p>
          {serviceName} is designed for teachers and education professionals. It is not directed at
          children under 13 (or 16 in the EU where applicable). We do not knowingly collect personal
          information from children. If you believe a child has provided us personal information,
          contact us and we will delete it.
        </p>
      </section>

      <section>
        <h2>11. Changes to this policy</h2>
        <p>
          We may update this Privacy Policy from time to time. We will post the updated version on
          this page and update the &quot;Last updated&quot; date. Material changes may be communicated
          by email or in-app notice where appropriate.
        </p>
      </section>

      <section>
        <h2>12. Contact</h2>
        <p>
          Questions about this Privacy Policy or our data practices:
          <br />
          <a href={`mailto:${contactEmail}`}>{contactEmail}</a>
          <br />
          {physicalAddress}
        </p>
        <p>
          See also our <Link href="/terms">Terms of Service</Link>.
        </p>
      </section>

      <p className="text-xs text-text-secondary">Effective date: {effectiveDate}</p>
    </>
  );
}
